### PR TITLE
Update- bash function p() to print filepath.

### PR DESCRIPTION
**Pull request by ipstone**
Hello, I tweaked the p() function in the README to work on mac-osx. Also make the function more structural, providing printing/returning the found pdf file name/path. Thanks for this awesome tool!

### CODE REVIEW

**Comment by bellecp** [comment]
What was the issue you fixed? To handle spaces in filenames?

**Comment by bellecp** [comment]
My understanding is that you fixed an issue arising because of your modification to echo the filename. Can you confirm that the code given in README works fine on OSX with filenames that include spaces?

Echoing the filename could be a nice addition indeed!

**Comment by bellecp** [comment]
Closing this; I prefer to keep the same bash code for both GNU/Linux and OSX as it is now in the current README. Thanks for the proposal though.

**Comment by ipstone** [comment]
no problem, thanks for creating this tool!

**Pull request closed without merging**
